version: "3.2"  
services: 
  influx:   
    image: influxdb   
    volumes:     
      - influx:/var/lib/influxdb
    ports:
      - target: 8086
        published: 8086
    networks:
      - host
    deploy: 
      replicas: 1      
      placement:
         constraints:
           - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - target: 8080
        published: 8080
    depends_on:
       - influx
    deploy:
      mode: global
networks:
  frontend:
  backend:
volumes:
  influx:
    driver: local

